moj_blog/urls.py
from django.urls import path
from . import views

app_name='moj_blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('moj_blog/nowy', views.nowy, name='nowy'),
    path('moj_blog/<int:pk>', views.wpis, name='wpis'),
    path('moj_blog/<int:pk>/edit', views.edycja, name='edycja'),
]



#localhost:8000/5/

rykowisko_proj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.auth import views
from moj_blog import views as bv

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moj_blog.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('accounts/rejestracja/', bv.rejestracja_view, name='rejestracja'),
]

moj_blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    autor = models.CharField(max_length=30)
    tytul = models.CharField(max_length=100)
    tresc = models.TextField()
    data_publikacji = models.DateTimeField()

moj_blog/forms.py
from django import forms
from .models import Post

from django.contrib.auth import (
    authenticate,
    get_user_model
)
User = get_user_model()

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('tytul', 'tresc')

class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label="Email adress")
    email2 = forms.EmailField(label="Confirm adress")
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'email2',
            'password'

        ]
def clean(self, *args, **kwargs):
    email = self.cleaned_data.get('email')
    email2 = self.cleaned_data.get('email2')
    if email != email2:
        raise forms.ValidationError('Email must match')
    email_qs = User.objects.filter(email=email)
    if email_qs.exist():
        raise forms.ValidationError('This email has already been registered')
    return super(UserRegisterForm, self).clean(*args, **kwargs)

moj_blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Post
from django.utils import timezone
from django.shortcuts import redirect
from .forms import PostForm, UserRegisterForm
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login


def index(request):
    posty = Post.objects.filter(data_publikacji__lte=timezone.now()).order_by(
        "data_publikacji"
    )
    return render(request, "moj_blog/index.html", {"posts": posty})

@login_required
def nowy(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.data_publikacji = timezone.now()
            post.save()
            return redirect('moj_blog:wpis', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'moj_blog/edycja.html', {'form': form})


def wpis(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'moj_blog/wpis.html', {'post': post})

@login_required
def edycja(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.data_publikacji = timezone.now()
            post.save()
            return redirect('moj_blog:wpis', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'moj_blog/edycja.html', {'form': form})

def rejestracja_view(request):
    next = request.GET.get('next')
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        if next:
            return redirect(next)
        return redirect('/')
    else:
        form =  UserRegisterForm()
    return render(request, 'moj_blog/rejestracja.html', {'form': form})

moj_blog/templates/moj_blog/baza.html
{% load static %}
<html>
    <head>
        <title>Moj blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'moj_blog:nowy' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                <p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
            {% else %}
                <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
                <a href="{% url 'rejestracja' %}" class="top-menu"><span class="glyphicon glyphicon-tower"></span></a>
            {% endif %}
            <h1><a href="/">Mój Blog</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

moj_blog/templates/moj_blog/edycja.html
{% extends 'moj_blog/baza.html' %}
{% block content %}

<h2>Edycja posta</h2>
<form method="POST" class='post-form'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class='save btn-default'>Save</button>
</form>

{% endblock content %}

moj_blog/templates/moj_blog/index.html
{% extends 'moj_blog/baza.html' %}
{% block content %}


{% for post in posts %}
    <div>
        <div>
            {{ post.data_publikacji }}
        </div>
        <h1><a href="{% url 'moj_blog:wpis' pk=post.pk %}">
        {{ post.tytul | linebreaksbr }}</a></h1>
    </div>
{% endfor %}

{% endblock content %}

moj_blog/templates/moj_blog/rejestracja.html
{% extends 'moj_blog/baza.html' %}
{% block content %}
<h2>Zarejestruj sie</h2>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" />
</form>
{% endblock content %}

moj_blog/templates/moj_blog/wpis.html
{% extends 'moj_blog/baza.html' %}
{% block content %}

<div class='post'> 
{% if post.data_publikacji %}
    <div class='date'>
        {{ post.data_publikacji }}
    </div>
{% endif %}
<a class='btn btn-default' href="{% url 'moj_blog:edycja' pk=post.pk %}">
<span class='glyphicon glyphicon-pencil'</span></a>
<h1>{{ post.tytul }}</h1>
<p>{{ post.tresc | linebreaksbr }}</p>
</div>


{% endblock content %}